apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CloudWithVarJosh/app1-config.git
    targetRevision: HEAD
    path: app1-helm
    helm:
      releaseName: app1
  destination:
    server: https://kubernetes.default.svc
    namespace: app1-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
