apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  namespace: app1-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Namespace
metadata:
  name: app1-ns