apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deploy
  namespace: product1-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
        - name: be-container
          image: cloudwithvarjosh/product1-be:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
