apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app1-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: cloudwithvarjosh/app1-backend:v1.0.0
          ports:
            - containerPort: 5000
