apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product1-root
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/CloudWithVarJosh/product1-fe-config.git
      targetRevision: main
      path: argo

    - repoURL: https://github.com/CloudWithVarJosh/product1-be-config.git
      targetRevision: main
      path: argo

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true